# Generated by Django 5.2 on 2025-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_books', models.ManyToManyField(blank=True, to='books.book')),
                ('ordered_menu_items', models.ManyToManyField(blank=True, to='menu.menuitem')),
            ],
        ),
    ]
